<a href="https://colab.research.google.com/github/banteamlak1888/Data-Processesnig-/blob/main/dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from collections import Counter

In [ ]:
import pandas as pd
# Upload 0MLT_Annotiated_Data.xlsx
DATA_PATH = "/content/00MLT_Annotiated_Data.xlsx"

df = pd.read_excel(DATA_PATH, sheet_name="Sheet1", engine="openpyxl")

print("Shape:", df.shape)
print("Columns:", list(df.columns))
df.tail(400)
#df.head(7)
#df.tail(7)

Shape: (95449, 4)
Columns: ['Sent_Num', 'WOrd', 'POS_Tag', 'NER_Tag']

       Sent_Num      WOrd POS_Tag NER_Tag
95049     10373    አእመርኩከ       V       O
95050     10373      እምኵሉ    CADJ       O
95051     10373       ወጸጋ      CN       O
95052     10373      ረከብከ       V       O
95053     10373     በቅድሜየ     PRO       O
...         ...       ...     ...     ...
95444     10399         ።    PUNC       O
95445     10400   ወኢይሥውዑ       PV  B-MISC
95446     10400  ለአማልክቲሆሙ       N  B-MISC
95447     10400   ወኢይጼውዑከ      PV       O
95448     10400         ።    PUNC       O

[400 rows x 4 columns]

In [ ]:
# 1. Missing values
print("Missing values per column:\n", df.isnull().sum())
missing_rows = df[df.isnull().any(axis=1)]
print(f"\n{len(missing_rows)} rows have at least one missing field:")
display(missing_rows)

Missing values per column:
 Sent_Num    0
WOrd        0
POS_Tag     0
NER_Tag     0
dtype: int64

0 rows have at least one missing field:

Empty DataFrame
Columns: [Sent_Num, WOrd, POS_Tag, NER_Tag]
Index: []

Sent_Num continity

In [ ]:
# 2. Sent_Num continuity (report gaps, do NOT auto-fix -- verify against source)
sent_ids = sorted(pd.to_numeric(df["Sent_Num"], errors='coerce').dropna().astype(int).unique())
gaps = [(sent_ids[i], sent_ids[i+1]) for i in range(len(sent_ids)-1)
        if sent_ids[i+1] - sent_ids[i] > 1]
print(f"\nTotal unique sentences: {len(sent_ids)}")
print(f"Sent_Num range: {sent_ids[0]} to {sent_ids[-1]}")
print(f"Gaps in numbering ({len(gaps)} found):", gaps[:10], "..." if len(gaps) > 10 else "")

Total unique sentences: 10401
Sent_Num range: 0 to 10400
Gaps in numbering (0 found): []

In [ ]:
import pandas as pd

# Read your annotated corpus file
#df = pd.read_excel("MLT_Clean_Annotated_Data.xlsx")

# Handle structural data sanitization
df['WOrd'] = df['WOrd'].astype(str).str.strip()
df['POS_Tag'] = df['POS_Tag'].astype(str).str.strip()

# Compute the counts requested by your team
total_words = len(df['WOrd'])
unique_words = df['WOrd'].nunique()
unique_tags = df['POS_Tag'].nunique()

# Print the target output strings cleanly
print(f"Total Words found : {total_words}")
print(f"Unique words in corpus: {unique_words}")
print(f"Unique tags in corpus: {unique_tags}")

Total Words found : 95449
Unique words in corpus: 11313
Unique tags in corpus: 164

In [ ]:
import pandas as pd

# Load your cleaned corpus file
#df = pd.read_excel("MLT_Clean_Annotated_Data.xlsx")

# Calculate metrics
total_tokens = len(df)
total_sentences = df['Sent_Num'].nunique()

print(f"📊 Total Number of Tokens (Rows): {total_tokens}")
print(f"📝 Total Number of Correct Sentences: {total_sentences}")

📊 Total Number of Tokens (Rows): 95449
📝 Total Number of Correct Sentences: 10401

In [ ]:
import pandas as pd

# 1. Load your dataset
#df = pd.read_excel("MLT_Clean_Annotated_Data.xlsx")

# 2. Enforce clean string formats on your feature column
df['POS_Tag'] = df['POS_Tag'].astype(str).str.strip()

# 3. Calculate value counts and percentage shares for all tags
pos_counts = df['POS_Tag'].value_counts()
pos_percentages = df['POS_Tag'].value_counts(normalize=True) * 100

# 4. Combine metrics into a clean distribution DataFrame
pos_distribution = pd.DataFrame({
    'Count': pos_counts,
    'Percentage (%)': pos_percentages
})

# 5. Configure Pandas to display ALL rows without truncation (...)
print("🧱 ===============================================================")
print("📊   COMPLETE CORPUS PARTITION: ALL 164 POS TAGS BEFORE MERGING")
print("===============================================================")

with pd.option_context('display.max_rows', None, 'display.max_columns', None, 'display.float_format', '{:.6f}'.format):
    print(pos_distribution)

print("===============================================================")
print(f"✅ Displayed all {len(pos_distribution)} rows sequentially.")
print("The top 100 represent your core; the bottom 64 are your rare targets.")
print("===============================================================")

🧱 ===============================================================
📊   COMPLETE CORPUS PARTITION: ALL 164 POS TAGS BEFORE MERGING
===============================================================
         Count  Percentage (%)
POS_Tag
N        25285       26.490587
PUNC     10192       10.677954
V         9440        9.890098
P         6602        6.916783
CNC       4494        4.708274
NC        4490        4.704083
CV        4054        4.247294
PN        3380        3.541158
PP        3367        3.527538
CVC       2957        3.097990
ADJ       2920        3.059225
PRO       2070        2.168697
C         1920        2.011545
CN        1705        1.786294
NUM       1052        1.102159
PVC        988        1.035108
VDM        948        0.993201
PRON       795        0.832906
PV         732        0.766902
DM         702        0.735471
NNP        696        0.729185
ADV        651        0.682040
CPDM       497        0.520697
CP         489        0.512315
PC         463        0.485076
AD         358        0.375069
PNC        303        0.317447
CADJ       292        0.305923
CPRON      281        0.294398
NCE        273        0.286017
AV         263        0.275540
CNUM       251        0.262968
INTRJ      197        0.206393
CNE        185        0.193821
CPN        155        0.162390
PDM        154        0.161343
VN         136        0.142484
CVNIE      130        0.136198
CCOP       130        0.136198
CPC        108        0.113149
CVDM       101        0.105816
NI          96        0.100577
CDM         76        0.079624
ADO         63        0.066004
O           47        0.049241
CPRO        47        0.049241
POS         43        0.045050
COP         42        0.044003
ADB         41        0.042955
CNEL        41        0.042955
CADVCEL     39        0.040860
VC          35        0.036669
CINTRJ      33        0.034573
PPPP        32        0.033526
CPP         31        0.032478
NADJ        30        0.031430
CPNE        30        0.031430
COPO        29        0.030383
PADJ        28        0.029335
VI          28        0.029335
CCO         24        0.025144
PRONC       23        0.024097
ADVI        22        0.023049
PPE         22        0.023049
CPVNI       20        0.020954
DEM         20        0.020954
NCEL        19        0.019906
PADV        18        0.018858
CVNIEL      18        0.018858
CNCEL       14        0.014668
CAD         13        0.013620
CC          13        0.013620
CNCELC      13        0.013620
PVCE        12        0.012572
CPVCE       12        0.012572
CADV        11        0.011524
PPN         11        0.011524
CPV         10        0.010477
PPOS        10        0.010477
CPADJ        9        0.009429
PNE          9        0.009429
CPPRON       9        0.009429
PART         9        0.009429
VB           8        0.008381
CCPC         8        0.008381
AMBI         8        0.008381
PNUM         7        0.007334
CPNEL        6        0.006286
CPVNIL       6        0.006286
CNDM         6        0.006286
CPROE        6        0.006286
PVI          5        0.005238
VNIE         5        0.005238
ADVB         5        0.005238
CCPE         5        0.005238
NP           4        0.004191
PPADV        4        0.004191
CCPEL        4        0.004191
PPRO         4        0.004191
===============================================================
✅ Displayed all 99 rows sequentially.
The top 100 represent your core; the bottom 64 are your rare targets.
===============================================================

In [ ]:
import pandas as pd
from IPython.display import HTML
# 1. Load your dataset
# (Make sure to replace this filename with your actual filename if it's different)
#df = pd.read_excel("MLT_Clean_Annotated_Data.xlsx")
df['POS_Tag'] = df['POS_Tag'].astype(str).str.strip()

# 2. Get the exact value counts from your distribution list
pos_counts = df['POS_Tag'].value_counts()
top_100_tags = set(pos_counts.head(100).index)

# 3. Explicit Linguistic Mapping for the 41 Rare Tags into the closest Top-100 Parents
# This maps every tag with a count of 3, 2, or 1 to its nearest structural counterpart.
rare_tags_mapping = {
    # --- Tags with Count 3 ---
    'CPNUM': 'CNUM',     # Complex Conjunction Numeral -> Conjunction Numeral
    'PPP': 'PP',         # Triple Preposition -> Preposition
    'PAD': 'AD',         # Preposition Adverb -> Adverb modifier
    'CPADV': 'ADV',      # Conjunction Preposition Adverb -> Adverb
    'CDMC': 'DM',        # Conjunction Demonstrative Clitic -> Demonstrative
    'CPOSC': 'POS',      # Conjunction Possessive Clitic -> Possessive
    'CNCE': 'CNC',       # Conjunction Noun Enclitic variant -> Conjunction Noun Clitic
    'CADJEL': 'ADJ',     # Complex Adjective with -EL suffix -> Adjective

    # --- Tags with Count 2 ---
    'PVN': 'VN',         # Preposition Verbal Noun -> Verbal Noun
    'PI': 'P',           # Preposition variant -> Preposition
    'NO': 'N',           # Noun variant -> Noun
    'CADO': 'AD',        # Conjunction Adverb -> Adverb modifier
    'CVCE': 'CVC',       # Conjunction Verb Clitic variant -> Conjunction Verb Clitic
    'PNEL': 'PN',        # Proper Noun with -EL suffix -> Proper Noun
    'CPPRONL': 'CPRON',  # Conjunction Pronoun variant -> Conjunction Pronoun
    'PPVN': 'VN',        # Preposition Verbal Noun variant -> Verbal Noun
    'ADJI': 'ADJ',       # Adjective variant -> Adjective
    'CPCV': 'CV',        # Conjunction Prefix Verb variant -> Conjunction Verb
    'PPV': 'PV',         # Preposition Prefix Verb variant -> Preposition Verb
    'CVIEL': 'CV',       # Conjunction Verb with -IEL suffix -> Conjunction Verb

    # --- Tags with Count 1 ---
    'PADVEL': 'ADV',     # Preposition Adverb with -EL suffix -> Adverb
    'NUMOR': 'NUM',      # Ordinal Numeral -> Numeral
    'CPNC': 'PNC',       # Conjunction Preposition Noun Clitic -> Preposition Noun Clitic
    'NUMC': 'NUM',       # Numeral Clitic -> Numeral
    'CPNADJ': 'ADJ',     # Conjunction Preposition Noun Adjective -> Adjective
    'PVNC': 'PNC',       # Preposition Verb Noun Clitic -> Preposition Noun Clitic
    'CNIEL': 'CN',       # Conjunction Noun with -IEL suffix -> Conjunction Noun
    'ADVC': 'ADV',       # Adverb Clitic -> Adverb
    'ADJC': 'ADJ',       # Adjective Clitic -> Adjective
    'POSNE': 'POS',      # Possessive Negative Enclitic -> Possessive
    'PVCEL': 'PVC',      # Preposition Verb Clitic with -EL suffix -> Preposition Verb Clitic
    'CPVCEL': 'CPC',     # Conjunction Preposition Verb variant -> Conjunction Preposition Clitic
    'NADVE': 'ADV',      # Noun Adverb variant -> Adverb
    'CADVI': 'ADV',      # Conjunction Adverb variant -> Adverb
    'CPPOSC': 'POS',     # Conjunction Possessive Clitic variant -> Possessive
    'VNIEL': 'VN',       # Verbal Noun with -IEL suffix -> Verbal Noun
    'VCO': 'V',          # Verb variant -> Verb
    'CPROIE': 'CPRO',    # Conjunction Pronoun variant -> Conjunction Pronoun
    'PNADJ': 'ADJ',      # Proper Noun Adjective combo -> Adjective
    'PRONI': 'PRON',     # Pronoun variant -> Pronoun
    'PPDM': 'P',         # Double Preposition Demonstrative -> Preposition
    'ADVIO': 'ADV'       # Adverb variant -> Adverb
}

# 4. Define the merge logic function
def apply_merging_strategy(tag):
    tag_str = str(tag).strip()

    # Check if the tag belongs to the 41 rare items targeted for merging
    if tag_str in rare_tags_mapping:
        return rare_tags_mapping[tag_str]

    return tag_str

print("🔄 --- Merging Audit Log (Mapping Traces) ---")
for rare, parent in rare_tags_mapping.items():
    print(f"Merged Rare Tag: [{rare:7}]  ➡️  Mapped to Top-100 High-Freq Parent: [{parent}]")

# 5. Apply the mapping to reshape the dataset
df['POS_Tag'] = df['POS_Tag'].apply(apply_merging_strategy)

# 6. Verify the final post-merge partition shape
final_pos_counts = df['POS_Tag'].value_counts()
final_unique_count = len(final_pos_counts)

print("\n🧱 ===============================================================")
print(f"📊   POST-MERGE CORPUS PARTITION: NEW TOTAL UNIQUE POS TAGS = {final_unique_count}")
print("===============================================================")
print(final_pos_counts.to_string())
print("===============================================================")

# 7. Save the perfectly reshaped 100-class Ge'ez corpus spreadsheet
output_filename = "MLT_Clean_Annotated_Data_100POS.xlsx"
df.to_excel(output_filename, index=False)
print(f"💾 Success! Reshaped 100-class dataset saved to: '{output_filename}'")

🔄 --- Merging Audit Log (Mapping Traces) ---
Merged Rare Tag: [CPNUM  ]  ➡️  Mapped to Top-100 High-Freq Parent: [CNUM]
Merged Rare Tag: [PPP    ]  ➡️  Mapped to Top-100 High-Freq Parent: [PP]
Merged Rare Tag: [PAD    ]  ➡️  Mapped to Top-100 High-Freq Parent: [AD]
Merged Rare Tag: [CPADV  ]  ➡️  Mapped to Top-100 High-Freq Parent: [ADV]
Merged Rare Tag: [CDMC   ]  ➡️  Mapped to Top-100 High-Freq Parent: [DM]
Merged Rare Tag: [CPOSC  ]  ➡️  Mapped to Top-100 High-Freq Parent: [POS]
Merged Rare Tag: [CNCE   ]  ➡️  Mapped to Top-100 High-Freq Parent: [CNC]
Merged Rare Tag: [CADJEL ]  ➡️  Mapped to Top-100 High-Freq Parent: [ADJ]
Merged Rare Tag: [PVN    ]  ➡️  Mapped to Top-100 High-Freq Parent: [VN]
Merged Rare Tag: [PI     ]  ➡️  Mapped to Top-100 High-Freq Parent: [P]
Merged Rare Tag: [NO     ]  ➡️  Mapped to Top-100 High-Freq Parent: [N]
Merged Rare Tag: [CADO   ]  ➡️  Mapped to Top-100 High-Freq Parent: [AD]
Merged Rare Tag: [CVCE   ]  ➡️  Mapped to Top-100 High-Freq Parent: [CVC]
Merged Rare Tag: [PNEL   ]  ➡️  Mapped to Top-100 High-Freq Parent: [PN]
Merged Rare Tag: [CPPRONL]  ➡️  Mapped to Top-100 High-Freq Parent: [CPRON]
Merged Rare Tag: [PPVN   ]  ➡️  Mapped to Top-100 High-Freq Parent: [VN]
Merged Rare Tag: [ADJI   ]  ➡️  Mapped to Top-100 High-Freq Parent: [ADJ]
Merged Rare Tag: [CPCV   ]  ➡️  Mapped to Top-100 High-Freq Parent: [CV]
Merged Rare Tag: [PPV    ]  ➡️  Mapped to Top-100 High-Freq Parent: [PV]
Merged Rare Tag: [CVIEL  ]  ➡️  Mapped to Top-100 High-Freq Parent: [CV]
Merged Rare Tag: [PADVEL ]  ➡️  Mapped to Top-100 High-Freq Parent: [ADV]
Merged Rare Tag: [NUMOR  ]  ➡️  Mapped to Top-100 High-Freq Parent: [NUM]
Merged Rare Tag: [CPNC   ]  ➡️  Mapped to Top-100 High-Freq Parent: [PNC]
Merged Rare Tag: [NUMC   ]  ➡️  Mapped to Top-100 High-Freq Parent: [NUM]
Merged Rare Tag: [CPNADJ ]  ➡️  Mapped to Top-100 High-Freq Parent: [ADJ]
Merged Rare Tag: [PVNC   ]  ➡️  Mapped to Top-100 High-Freq Parent: [PNC]
Merged Rare Tag: [CNIEL  ]  ➡️  Mapped to Top-100 High-Freq Parent: [CN]
Merged Rare Tag: [ADVC   ]  ➡️  Mapped to Top-100 High-Freq Parent: [ADV]
Merged Rare Tag: [ADJC   ]  ➡️  Mapped to Top-100 High-Freq Parent: [ADJ]
Merged Rare Tag: [POSNE  ]  ➡️  Mapped to Top-100 High-Freq Parent: [POS]
Merged Rare Tag: [PVCEL  ]  ➡️  Mapped to Top-100 High-Freq Parent: [PVC]
Merged Rare Tag: [CPVCEL ]  ➡️  Mapped to Top-100 High-Freq Parent: [CPC]
Merged Rare Tag: [NADVE  ]  ➡️  Mapped to Top-100 High-Freq Parent: [ADV]
Merged Rare Tag: [CADVI  ]  ➡️  Mapped to Top-100 High-Freq Parent: [ADV]
Merged Rare Tag: [CPPOSC ]  ➡️  Mapped to Top-100 High-Freq Parent: [POS]
Merged Rare Tag: [VNIEL  ]  ➡️  Mapped to Top-100 High-Freq Parent: [VN]
Merged Rare Tag: [VCO    ]  ➡️  Mapped to Top-100 High-Freq Parent: [V]
Merged Rare Tag: [CPROIE ]  ➡️  Mapped to Top-100 High-Freq Parent: [CPRO]
Merged Rare Tag: [PNADJ  ]  ➡️  Mapped to Top-100 High-Freq Parent: [ADJ]
Merged Rare Tag: [PRONI  ]  ➡️  Mapped to Top-100 High-Freq Parent: [PRON]
Merged Rare Tag: [PPDM   ]  ➡️  Mapped to Top-100 High-Freq Parent: [P]
Merged Rare Tag: [ADVIO  ]  ➡️  Mapped to Top-100 High-Freq Parent: [ADV]

🧱 ===============================================================
📊   POST-MERGE CORPUS PARTITION: NEW TOTAL UNIQUE POS TAGS = 99
===============================================================
POS_Tag
N          25285
PUNC       10192
V           9440
P           6602
CNC         4494
NC          4490
CV          4054
PN          3380
PP          3367
CVC         2957
ADJ         2920
PRO         2070
C           1920
CN          1705
NUM         1052
PVC          988
VDM          948
PRON         795
PV           732
DM           702
NNP          696
ADV          651
CPDM         497
CP           489
PC           463
AD           358
PNC          303
CADJ         292
CPRON        281
NCE          273
AV           263
CNUM         251
INTRJ        197
CNE          185
CPN          155
PDM          154
VN           136
CVNIE        130
CCOP         130
CPC          108
CVDM         101
NI            96
CDM           76
ADO           63
O             47
CPRO          47
POS           43
COP           42
ADB           41
CNEL          41
CADVCEL       39
VC            35
CINTRJ        33
PPPP          32
CPP           31
NADJ          30
CPNE          30
COPO          29
PADJ          28
VI            28
CCO           24
PRONC         23
ADVI          22
PPE           22
CPVNI         20
DEM           20
NCEL          19
PADV          18
CVNIEL        18
CNCEL         14
CAD           13
CC            13
CNCELC        13
PVCE          12
CPVCE         12
CADV          11
PPN           11
CPV           10
PPOS          10
CPADJ          9
PNE            9
CPPRON         9
PART           9
VB             8
CCPC           8
AMBI           8
PNUM           7
CPNEL          6
CPVNIL         6
CNDM           6
CPROE          6
PVI            5
VNIE           5
ADVB           5
CCPE           5
NP             4
PPADV          4
CCPEL          4
PPRO           4
===============================================================
💾 Success! Reshaped 100-class dataset saved to: 'MLT_Clean_Annotated_Data_100POS.xlsx'

In [ ]:
import base64
import pandas as pd
from IPython.display import HTML

def merge_pos_and_generate_download(input_excel_filename, output_excel_filename):
    """
    Transforms the 141 unique POS tagsets down to exactly 100 base parent roots
    and automatically builds an inline, clickable browser download hyperlink.
    """
    # 1. Load the original dataset
    df = pd.read_excel(input_excel_filename)

    # Secure string properties only on the target column to protect other column data types
    df['POS_Tag'] = df['POS_Tag'].astype(str).str.strip()

    # 2. Precise linguistic mapping for the 41 rare outliers (counts of 3, 2, and 1)
    rare_tags_mapping = {
        # --- Rare Tags with Count 3 ---
        'CPNUM': 'CNUM', 'PPP': 'PP', 'PAD': 'AD', 'CPADV': 'ADV',
        'CDMC': 'DM', 'CPOSC': 'POS', 'CNCE': 'CNC', 'CADJEL': 'ADJ',

        # --- Rare Tags with Count 2 ---
        'PVN': 'VN', 'PI': 'P', 'NO': 'N', 'CADO': 'AD', 'CVCE': 'CVC',
        'PNEL': 'PN', 'CPPRONL': 'CPRON', 'PPVN': 'VN', 'ADJI': 'ADJ',
        'CPCV': 'CV', 'PPV': 'PV', 'CVIEL': 'CV',

        # --- Rare Tags with Count 1 ---
        'PADVEL': 'ADV', 'NUMOR': 'NUM', 'CPNC': 'PNC', 'NUMC': 'NUM',
        'CPNADJ': 'ADJ', 'PVNC': 'PNC', 'CNIEL': 'CN', 'ADVC': 'ADV',
        'ADJC': 'ADJ', 'POSNE': 'POS', 'PVCEL': 'PVC', 'CPVCEL': 'CPC',
        'NADVE': 'ADV', 'CADVI': 'ADV', 'CPPOSC': 'POS', 'VNIEL': 'VN',
        'VCO': 'V', 'CPROIE': 'CPRO', 'PNADJ': 'ADJ', 'PRONI': 'PRON',
        'PPDM': 'P', 'ADVIO': 'ADV'
    }

    # 3. Apply transformation mapping specifically to the POS_Tag target layer
    df['POS_Tag'] = df['POS_Tag'].replace(rare_tags_mapping)

    # 4. Save the cleanly modified structural matrix workbook locally
    df.to_excel(output_excel_filename, index=False)
    print(f"📊 Matrix Reshaped Successfully! New unique POS tags count: {df['POS_Tag'].nunique()}")
    print("🔒 All other data columns remained perfectly preserved.")

    # 5. GENERATE BROWSER DOWNLOAD LINK (Fixes automated local directory blockage)
    with open(output_excel_filename, 'rb') as f:
        excel_bytes = f.read()

    b64_encoded_excel = base64.b64encode(excel_bytes).decode()
    download_href = (
        f'<a href="data:application/vnd.openxmlformats-officedocument.spreadsheetml.sheet;base64,{b64_encoded_excel}" '
        f'download="{output_excel_filename}" style="font-weight: bold; color: #1E88E5; font-size: 16px;">'
        f'👉 Click Here to Download "{output_excel_filename}" Directly To Your Machine 👈</a>'
    )

    return HTML(download_href)

# --- Execute Code & Display Clickable Link ---
# Point this precisely to your current file name directory path
source_dataset = "/content/00MLT_Annotiated_Data.xlsx" # Corrected typo here
target_dataset = "MLT_Clean_Annotated_Data_100POS.xlsx"

# Run mapping pipeline and render the download interface
merge_pos_and_generate_download(source_dataset, target_dataset)

📊 Matrix Reshaped Successfully! New unique POS tags count: 99
🔒 All other data columns remained perfectly preserved.

In [ ]:
import pandas as pd

# Load your corpus workbook
df = pd.read_excel("0MLT__Data.xlsx")

# Enforce clean string formats across the entity column
df['NER_Tag'] = df['NER_Tag'].astype(str).str.strip()

# 1. Isolate the absolute unique tags present in the corpus
unique_ner_tags = sorted(df['NER_Tag'].unique())

print("📋 ===============================================================")
print(f"📊 TOTAL UNIQUE NER TAGS DETECTED: {len(unique_ner_tags)}")
print("===============================================================")
for idx, tag in enumerate(unique_ner_tags, 1):
    print(f"  {idx:2}. Tag Signature: [{tag}]")
print("===============================================================")

# 2. Advanced Structural Rule Verification: Trace Unpaired I- Tags
# Checks if an Inside tag exists without its corresponding Beginning tag block
unpaired_i_tags = []
for tag in unique_ner_tags:
    if tag.startswith('I-'):
        expected_b_tag = tag.replace('I-', 'B-')
        if expected_b_tag not in unique_ner_tags:
            unpaired_i_tags.append((tag, expected_b_tag))

if unpaired_i_tags:
    print("⚠️ STRUCTURAL ANOMALY DETECTED (BIO Scheme Violation):")
    for i_tag, b_tag in unpaired_i_tags:
        print(f"  Missing parent tag: [{b_tag}] for existing inner layer -> [{i_tag}]")
else:
    print("✨ Integrity Validation Passed: All 'I-' tags possess valid 'B-' structural parent roots.")
print("===============================================================")

📋 ===============================================================
📊 TOTAL UNIQUE NER TAGS DETECTED: 40
===============================================================
   1. Tag Signature: [B-ANG]
   2. Tag Signature: [B-BOOK]
   3. Tag Signature: [B-CNTRY]
   4. Tag Signature: [B-DOMANM]
   5. Tag Signature: [B-FIRE]
   6. Tag Signature: [B-GOD]
   7. Tag Signature: [B-LAND]
   8. Tag Signature: [B-LIGHT]
   9. Tag Signature: [B-MISC]
  10. Tag Signature: [B-ORG]
  11. Tag Signature: [B-PER]
  12. Tag Signature: [B-PLANT]
  13. Tag Signature: [B-PROD]
  14. Tag Signature: [B-RIVER]
  15. Tag Signature: [B-SEA]
  16. Tag Signature: [B-SKY]
  17. Tag Signature: [B-TIME]
  18. Tag Signature: [B-WIND]
  19. Tag Signature: [B-WLDANM]
  20. Tag Signature: [CN]
  21. Tag Signature: [I-ANG]
  22. Tag Signature: [I-BOOK]
  23. Tag Signature: [I-CNTRY]
  24. Tag Signature: [I-DOMANM]
  25. Tag Signature: [I-FIRE]
  26. Tag Signature: [I-GOD]
  27. Tag Signature: [I-LAND]
  28. Tag Signature: [I-LIGHT]
  29. Tag Signature: [I-MISC]
  30. Tag Signature: [I-ORG]
  31. Tag Signature: [I-PER]
  32. Tag Signature: [I-PLANT]
  33. Tag Signature: [I-PROD]
  34. Tag Signature: [I-RIVER]
  35. Tag Signature: [I-SEA]
  36. Tag Signature: [I-SKY]
  37. Tag Signature: [I-TIME]
  38. Tag Signature: [I-WIND]
  39. Tag Signature: [I-WLDANM]
  40. Tag Signature: [O]
===============================================================
✨ Integrity Validation Passed: All 'I-' tags possess valid 'B-' structural parent roots.
===============================================================

In [ ]:
import pandas as pd

# 1. Load the dataset
#file_name = "MLT_Clean_Annotated_Data_100POS.xlsx"
df = pd.read_excel(file_name)

# Ensure string cleanup
df['NER_Tag'] = df['NER_Tag'].astype(str).str.strip()

# 2. Locate the row(s) where the POS tag leaked into the NER column
leaked_rows = df[df['NER_Tag'] == 'CN']

print("🔍 --- Locating Leaked 'CN' in NER Column ---")
if not leaked_rows.empty:
    print(f"Found {len(leaked_rows)} row(s) with the invalid 'CN' NER tag:")
    print(leaked_rows)

    # 3. Auto-fix: Correct 'CN' to 'O' (or the correct default fallback for outside words)
    # Most tokens that are coordinate nouns but not named entities belong to 'O'
    df.loc[df['NER_Tag'] == 'CN', 'NER_Tag'] = 'O'
    print("\n✅ Successfully fixed! Replaced invalid 'CN' tags with 'O'.")

    # 4. Save the fully sanitized dataset back to Excel
    df.to_excel(file_name, index=False)
    print(f"💾 Cleaned dataset updated and saved to: '{file_name}'")

    # 5. Verify the new count
    new_unique_ner = sorted(df['NER_Tag'].unique())
    print(f"\n📊 Updated Unique NER Tags Count: {len(new_unique_ner)} (Should be exactly 39)")
else:
    print("No leaked 'CN' tags found. Check if the file name is matching your latest data sheet.")

In [ ]:
import pandas as pd

# Load your 100-POS dataset file
dataset_file = "0MLT__Data.xlsx"
df = pd.read_excel(dataset_file)

# Replaces the misplaced POS tag in the NER column with a valid 'O' tag
df['NER_Tag'] = df['NER_Tag'].astype(str).str.strip().replace('CN', 'O')

# Save the finalized, verified corpus configuration
df.to_excel(dataset_file, index=False)

print("✨ Cleanup Complete!")
print(f"📊 Verified unique NER tags left: {df['NER_Tag'].nunique()} (Exactly 39 valid classes).")

✨ Cleanup Complete!
📊 Verified unique NER tags left: 39 (Exactly 39 valid classes).

In [ ]:
import base64
import pandas as pd
from IPython.display import HTML

def transform_to_20_classes_and_download(input_excel_file, output_excel_file):
    """
    Collapses 39 BIO tag boundaries into 20 clean entity categories
    and automatically builds an inline browser download hyperlink.
    """
    # 1. Load the original dataset layout
    df = pd.read_excel(input_excel_file)

    # Cast to safe string type to prevent floating-point disruptions
    df['NER_Tag'] = df['NER_Tag'].astype(str).str.strip()

    # 2. Define the exact categorical mapping function
    def strip_bio_prefix(tag):
        tag_str = str(tag).strip()

        # If outside or clean, return as is
        if tag_str == 'O' or tag_str == 'nan':
            return 'O'

        # Strip BIO boundaries (e.g., 'B-GOD' or 'I-GOD' becomes 'GOD')
        if tag_str.startswith('B-') or tag_str.startswith('I-'):
            return tag_str[2:]

        return tag_str

    # 3. Create the clean 20-class feature vector column
    # We create a new column to leave your original data columns perfectly safe
    df['NER_Class_20'] = df['NER_Tag'].apply(strip_bio_prefix)

    # 4. Save the modified dataset workbook matrix locally
    df.to_excel(output_excel_file, index=False)

    print("🧱 ===============================================================")
    print(f"📊   STAGE 1 RE-MAPPING COMPLETE: UNIQUE NER TARGET CLASSES = {df['NER_Class_20'].nunique()}")
    print("===============================================================")
    print(df['NER_Class_20'].value_counts().to_string())
    print("===============================================================")
    print("🔒 All other data paths remained perfectly preserved.")

    # 5. GENERATE INSTANT BROWSER DOWNLOAD LINK
    with open(output_excel_file, 'rb') as f:
        excel_bytes = f.read()

    b64_encoded_excel = base64.b64encode(excel_bytes).decode()
    download_href = (
        f'<a href="data:application/vnd.openxmlformats-officedocument.spreadsheetml.sheet;base64,{b64_encoded_excel}" '
        f'download="{output_excel_file}" style="font-weight: bold; color: #E65100; font-size: 16px;">'
        f'👉 Click Here to Download "{output_excel_file}" Directly To Your Machine 👈</a>'
    )

    return HTML(download_href)

# --- Runtime Invocation Configuration ---
# Match these filenames to your workspace path
source_sheet = "0MLT__Data.xlsx"
target_sheet = "0MLT__Data_20NER.xlsx"

# Run mapping pipeline and render the download interface
transform_to_20_classes_and_download(source_sheet, target_sheet)

🧱 ===============================================================
📊   STAGE 1 RE-MAPPING COMPLETE: UNIQUE NER TARGET CLASSES = 20
===============================================================
NER_Class_20
O         36767
MISC      26258
PER        5463
TIME       3953
LAND       3773
PROD       2534
GOD        2394
BOOK       2013
WIND       1857
PLANT      1687
ORG        1402
SEA        1263
WLDANM     1252
RIVER      1141
DOMANM     1111
CNTRY       822
SKY         745
FIRE        456
LIGHT       387
ANG         171
===============================================================
🔒 All other data paths remained perfectly preserved.

In [ ]:
import base64
import numpy as np
import pandas as pd
from IPython.display import HTML

def calculate_ner_weights_and_download(input_excel_file, output_txt_file):
    """
    Calculates inverse-frequency class weights for the 39-class BIO column
    to eliminate model overfitting without altering the target labels.
    """
    # 1. Load the pristine dataset sheet
    df = pd.read_excel(input_excel_file)
    df['NER_Tag'] = df['NER_Tag'].astype(str).str.strip()

    # 2. Extract total token count and per-class frequencies
    total_tokens = len(df)
    class_counts = df['NER_Tag'].value_counts()
    unique_classes = sorted(df['NER_Tag'].unique())
    num_classes = len(unique_classes)

    # 3. Calculate inverse frequency class weights formula: Total / (Num_Classes * Class_Count)
    weights_dict = {}
    print("📊 --- Calculated Loss-Penalties (Class Weights) ---")
    for cls in unique_classes:
        count = class_counts[cls]
        # Mathematical inverse balance factor
        weight = total_tokens / (num_classes * count)
        weights_dict[cls] = round(weight, 4)
        print(f"Label: [{cls:10}] | Frequency Count: {count:5} | Loss Weight Multiplier: {weight:.4f}")

    # 4. Format as a clean, ready-to-use PyTorch/TensorFlow Python code string
    code_string = "import torch\n\n"
    code_string += "# Copy-paste this ordered class list directly into your Dataset Class:\n"
    code_string += f"NER_CLASSES = {unique_classes}\n\n"
    code_string += "# Copy-paste this tensor directly into your CrossEntropyLoss(weight=NER_WEIGHTS_TENSOR):\n"

    ordered_weights = [weights_dict[cls] for cls in unique_classes]
    code_string += f"NER_WEIGHTS_TENSOR = torch.tensor({ordered_weights}, dtype=torch.float)\n"

    # 5. Write the script matrix block to a text file
    with open(output_txt_file, 'w', encoding='utf-8') as f:
        f.write(code_string)

    print("\n" + "="*60)
    print(f"✅ Success! Your Deep Learning training parameters are computed.")
    print("="*60)

    # 6. Generate an instant browser download link for the text file
    with open(output_txt_file, 'rb') as f:
        file_bytes = f.read()

    b64_encoded = base64.b64encode(file_bytes).decode()
    download_href = (
        f'<a href="data:text/plain;base64,{b64_encoded}" '
        f'download="{output_txt_file}" style="font-weight: bold; color: #0288D1; font-size: 16px;">'
        f'👉 Click Here to Download "{output_txt_file}" for Your Model Code 👈</a>'
    )

    return HTML(download_href)

# --- Runtime Trigger Setup ---
source_workbook = "0MLT__Data.xlsx"
target_code_file = "ner_model_weights.txt"

# Execute calculation and display the download text link
calculate_ner_weights_and_download(source_workbook, target_code_file)

📊 --- Calculated Loss-Penalties (Class Weights) ---
Label: [B-ANG     ] | Frequency Count:   166 | Loss Weight Multiplier: 14.7434
Label: [B-BOOK    ] | Frequency Count:  1097 | Loss Weight Multiplier: 2.2310
Label: [B-CNTRY   ] | Frequency Count:   796 | Loss Weight Multiplier: 3.0746
Label: [B-DOMANM  ] | Frequency Count:  1107 | Loss Weight Multiplier: 2.2108
Label: [B-FIRE    ] | Frequency Count:   348 | Loss Weight Multiplier: 7.0328
Label: [B-GOD     ] | Frequency Count:  2377 | Loss Weight Multiplier: 1.0296
Label: [B-LAND    ] | Frequency Count:  3565 | Loss Weight Multiplier: 0.6865
Label: [B-LIGHT   ] | Frequency Count:   368 | Loss Weight Multiplier: 6.6506
Label: [B-MISC    ] | Frequency Count: 25898 | Loss Weight Multiplier: 0.0945
Label: [B-ORG     ] | Frequency Count:  1339 | Loss Weight Multiplier: 1.8278
Label: [B-PER     ] | Frequency Count:  5314 | Loss Weight Multiplier: 0.4606
Label: [B-PLANT   ] | Frequency Count:  1319 | Loss Weight Multiplier: 1.8555
Label: [B-PROD    ] | Frequency Count:  2478 | Loss Weight Multiplier: 0.9877
Label: [B-RIVER   ] | Frequency Count:   725 | Loss Weight Multiplier: 3.3757
Label: [B-SEA     ] | Frequency Count:  1071 | Loss Weight Multiplier: 2.2852
Label: [B-SKY     ] | Frequency Count:   591 | Loss Weight Multiplier: 4.1411
Label: [B-TIME    ] | Frequency Count:  2598 | Loss Weight Multiplier: 0.9420
Label: [B-WIND    ] | Frequency Count:  1013 | Loss Weight Multiplier: 2.4160
Label: [B-WLDANM  ] | Frequency Count:  1249 | Loss Weight Multiplier: 1.9595
Label: [I-ANG     ] | Frequency Count:     5 | Loss Weight Multiplier: 489.4821
Label: [I-BOOK    ] | Frequency Count:   916 | Loss Weight Multiplier: 2.6718
Label: [I-CNTRY   ] | Frequency Count:    26 | Loss Weight Multiplier: 94.1312
Label: [I-DOMANM  ] | Frequency Count:     4 | Loss Weight Multiplier: 611.8526
Label: [I-FIRE    ] | Frequency Count:   108 | Loss Weight Multiplier: 22.6612
Label: [I-GOD     ] | Frequency Count:    17 | Loss Weight Multiplier: 143.9653
Label: [I-LAND    ] | Frequency Count:   208 | Loss Weight Multiplier: 11.7664
Label: [I-LIGHT   ] | Frequency Count:    19 | Loss Weight Multiplier: 128.8111
Label: [I-MISC    ] | Frequency Count:   360 | Loss Weight Multiplier: 6.7984
Label: [I-ORG     ] | Frequency Count:    63 | Loss Weight Multiplier: 38.8478
Label: [I-PER     ] | Frequency Count:   149 | Loss Weight Multiplier: 16.4256
Label: [I-PLANT   ] | Frequency Count:   368 | Loss Weight Multiplier: 6.6506
Label: [I-PROD    ] | Frequency Count:    56 | Loss Weight Multiplier: 43.7038
Label: [I-RIVER   ] | Frequency Count:   416 | Loss Weight Multiplier: 5.8832
Label: [I-SEA     ] | Frequency Count:   192 | Loss Weight Multiplier: 12.7469
Label: [I-SKY     ] | Frequency Count:   154 | Loss Weight Multiplier: 15.8923
Label: [I-TIME    ] | Frequency Count:  1355 | Loss Weight Multiplier: 1.8062
Label: [I-WIND    ] | Frequency Count:   844 | Loss Weight Multiplier: 2.8998
Label: [I-WLDANM  ] | Frequency Count:     3 | Loss Weight Multiplier: 815.8034
Label: [O         ] | Frequency Count: 36767 | Loss Weight Multiplier: 0.0666

============================================================
✅ Success! Your Deep Learning training parameters are computed.
============================================================